project_id = "qmkcgwgiqrmtqrxmxeam"

[functions.create-payment-intent]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.get-stripe-key]
verify_jwt = false

[functions.directions]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.generate-monthly-invoices]
verify_jwt = false

[functions.check-overdue-invoices]
verify_jwt = false

[functions.push-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
