project_id = "qmkcgwgiqrmtqrxmxeam"

[functions.create-payment-intent]
verify_jwt = false

[functions.capture-payment]
verify_jwt = false

[functions.get-stripe-key]
verify_jwt = false

[functions.directions]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false

[functions.place-details]
verify_jwt = false
